### ISSUE TITLE
adguardvpn-cli set-post-quantum

### ISSUE THREAD

**Issue by mjeshurun** [supersunho/docker-adguardvpn-cli#5]
I was looking for a way to auto-connect adguardvpn-cli docker when the app is started, so thank you for creating this docker app 🙏

A few months ago, adguardvpn-cli added an option to run the command `adguardvpn-cli config set-post-quantum on` to enable post quantum VPN protection. 

Is there an env variable we can add to your docker app that will auto enable this setting at app startup?

**Comment by supersunho** [comment]
Hi, @mjeshurun 
Thank you for your interest in my project. 
I’ll be updating a new version with that feature soon!

**Comment by supersunho** [comment]
I’ve just pushed an update. Please try version `1.4.5` or the `latest` tag. 
You can enable it by setting `ADGUARD_POST_QUANTUM="on"`. 
For detailed instructions, please refer to the README.md
Thanks! 🌝

**Comment by mjeshurun** [comment]
Thank you for updating the release so quickly 🙏
I think the `ADGUARD_POST_QUANTUM="on"` variable is not working properly.
I still see Set Post Quantum as off in the log, even though I set the variable to "on".

```
Current configuration:
        Data directory: /root/.local/share/adguardvpn-cli
        Mode: tun
        SOCKS port: 1080
        SOCKS host: 127.0.0.1
        SOCKS username: 
        DNS upstream: Default (provided by AdGuard VPN)
        Tunnel routing mode: auto
        Change system DNS: on
        Crash reporting: on
        Update channel: RELEASE
        Use QUIC: Default (off)
        Post-Quantum Cryptography: Default (off)
        Show hints: Default (on)
        Debug logging: Default (off)
        Show notifications: Default (off)
        Outbound interface override: not set
```

**Comment by supersunho** [comment]
Please check the your `.env `file. 
configuration might be incorrect. 
In my case, it’s set to “on” and works fine.

```
Current configuration:
        Data directory: /root/.local/share/adguardvpn-cli
        Mode: tun
        SOCKS port: 1080
        SOCKS host: 127.0.0.1
        SOCKS username:
        DNS upstream: 1.1.1.1
        Tunnel routing mode: auto
        Change system DNS: off
        Crash reporting: off
        Update channel: BETA
        Protocol: auto
        Post-Quantum Cryptography: on
        Show hints: on
        Debug logging: on
        Show notifications: on
        Outbound interface override: not set
```

**Comment by supersunho** [comment]
I can’t agree with that. It worked fine for me even after pulling the `latest` tag and running it. I’ll review this on Docker Hub.

**Comment by mjeshurun** [comment]
I tested again, but when I use release ":latest" the app downgrades again to 1.3.28 🤔
I can send you a screen video recording if seeing what's happening on my server will help you.

**Comment by mjeshurun** [comment]
Rechecked using `:latest` today and now it successfully pulled v1.4.5. 
I guess Docker Hub had a delay in distributing the newer version under `:latest`. 
Thank you.
